// Seeded demo data, ported verbatim from kbhatnagar1506/vouch-ui's
// src/data/seed.js. Used only by /demo — the real /dashboard route never
// imports this file. See docs/DASHBOARD.md.
import type { Subscription, Transaction, Budget, Connector, DashboardUser } from "@/lib/dashboard-types";

export const subscriptions: Subscription[] = [
  {
    id: "spotify",
    logo: "/assets/logos/spotify.svg",
    tint: "linear-gradient(150deg,#12241b 0%,#143a28 50%,#1db954 130%)",
    name: "Spotify",
    color: "#1db954",
    initial: "S",
    price: 11.99,
    cycle: "monthly",
    renewsIn: 2,
    card: "•••• 4021",
    status: "renew",
    usage30: 47,
    usageUnit: "plays",
    trend: "up",
    priceChange: 0,
    overlap: null,
    reason: "Renewed Spotify. 47 plays in the last 30 days, price unchanged.",
  },
  {
    id: "peloton",
    logo: null,
    tint: "linear-gradient(150deg,#241213 0%,#3a1418 50%,#df1c2f 130%)",
    name: "Peloton",
    color: "#df1c2f",
    initial: "P",
    price: 44.0,
    cycle: "monthly",
    renewsIn: 1,
    card: "closed",
    status: "hold",
    usage30: 0,
    usageUnit: "rides",
    trend: "down",
    priceChange: 15,
    overlap: "ClassPass",
    reason: "Held Peloton. 0 rides since July 3. Price rose 15% in June. You also pay for ClassPass.",
  },
  {
    id: "netflix",
    logo: "/assets/logos/netflix.svg",
    tint: "linear-gradient(150deg,#241012 0%,#3a1114 50%,#e50914 130%)",
    name: "Netflix",
    color: "#e50914",
    initial: "N",
    price: 15.49,
    cycle: "monthly",
    renewsIn: 6,
    card: "•••• 7788",
    status: "renew",
    usage30: 12,
    usageUnit: "hours watched",
    trend: "flat",
    priceChange: 0,
    overlap: null,
    reason: "Renewed Netflix. 12 hours watched this month, steady usage.",
  },
  {
    id: "chatgpt",
    logo: null,
    tint: "linear-gradient(150deg,#122320 0%,#123a30 50%,#10a37f 130%)",
    name: "ChatGPT Plus",
    color: "#10a37f",
    initial: "C",
    price: 20.0,
    cycle: "monthly",
    renewsIn: 9,
    card: "•••• 1902",
    status: "renew",
    usage30: 138,
    usageUnit: "sessions",
    trend: "up",
    priceChange: 0,
    overlap: null,
    reason: "Renewed ChatGPT Plus. 138 sessions this month, usage climbing.",
  },
  {
    id: "nyt",
    logo: "/assets/logos/nyt.svg",
    tint: "linear-gradient(150deg,#1a1a1e 0%,#26262c 60%,#3a3a44 130%)",
    name: "NYT",
    color: "#1a1a1a",
    initial: "T",
    price: 17.0,
    cycle: "monthly",
    renewsIn: 4,
    card: "closed",
    status: "ask",
    usage30: 3,
    usageUnit: "articles",
    trend: "down",
    priceChange: 25,
    overlap: null,
    reason: "3 articles in 30 days and the price just jumped 25% to $17. Worth keeping?",
  },
];

export const transactions: Transaction[] = [
  { id: "t1", merchant: "Peloton", kind: "declined", amount: 44.0, time: "just now", note: "Renewal hit closed card" },
  { id: "t2", merchant: "Spotify", kind: "out", amount: 11.99, time: "2 hours ago", note: "New card minted · charge approved" },
  { id: "t3", merchant: "ChatGPT Plus", kind: "out", amount: 20.0, time: "Yesterday", note: "Auto-renewed · 138 sessions" },
  { id: "t4", merchant: "NYT", kind: "declined", amount: 17.0, time: "Yesterday", note: "Held for your review" },
  { id: "t5", merchant: "Netflix", kind: "out", amount: 15.49, time: "3 days ago", note: "Auto-renewed" },
  { id: "t6", merchant: "Refund · Peloton", kind: "in", amount: 44.0, time: "Last week", note: "Prorated refund after cancel" },
];

export const budget: Budget = {
  monthlyCap: 120,
  spent: 67.48,
  saved: 44.0,
  lastMonth: 88.0,
  account: {
    bank: "Chase",
    name: "Total Checking",
    mask: "1847",
    balance: 3284.52,
    available: 3110.0,
    monthlyIncome: 4200.0,
  },
  lines: [
    { cat: "Streaming video", spent: 15.49, cap: 30, color: "#e50914" },
    { cat: "AI & tools", spent: 20.0, cap: 25, color: "#10a37f" },
    { cat: "News", spent: 17.0, cap: 20, color: "#1f3df0" },
    { cat: "Music & audio", spent: 11.99, cap: 15, color: "#0b8a5a" },
    { cat: "Fitness", spent: 0, cap: 45, color: "#c47d18" },
  ],
  upcoming: [
    { id: "u1", name: "Peloton", logo: null, initial: "P", color: "#df1c2f", amount: 44.0, dueInDays: 1, status: "hold", note: "Held — 0 rides. Confirm before it charges." },
    { id: "u2", name: "Spotify", logo: "/assets/logos/spotify.svg", initial: "S", color: "#1db954", amount: 11.99, dueInDays: 2, status: "renew", note: "Will auto-renew. New card minted." },
    { id: "u3", name: "NYT", logo: "/assets/logos/nyt.svg", initial: "T", color: "#1a1a1a", amount: 17.0, dueInDays: 4, status: "ask", note: "Price up 25% — Vouch will ask you." },
    { id: "u4", name: "Netflix", logo: "/assets/logos/netflix.svg", initial: "N", color: "#e50914", amount: 15.49, dueInDays: 6, status: "renew", note: "Will auto-renew." },
    { id: "u5", name: "ChatGPT Plus", logo: null, initial: "C", color: "#10a37f", amount: 20.0, dueInDays: 9, status: "renew", note: "Will auto-renew — heavy usage." },
  ],
  history: [
    { month: "Apr", spent: 108, saved: 0 },
    { month: "May", spent: 112, saved: 12 },
    { month: "Jun", spent: 121, saved: 8 },
    { month: "Jul", spent: 95, saved: 26 },
    { month: "Aug", spent: 88, saved: 33 },
    { month: "Sep", spent: 67, saved: 44 },
  ],
};

export const connectors: Connector[] = [
  { id: "lithic", name: "Lithic", initial: "L", color: "#1f3df0", logo: null, state: "connected", detail: "Card issuing · 5 active cards" },
  { id: "bank", name: "Bank account", initial: "B", color: "#0b8a5a", logo: null, state: "connected", detail: "Chase · funding source ••1847" },
  { id: "gmail", name: "Gmail", initial: "G", color: "#ea4335", logo: null, state: "connected", detail: "Receipts & renewal emails synced" },
  { id: "claude", name: "Claude", initial: "C", color: "#d97706", logo: "/assets/logos/claude.svg", state: "connected", detail: "MCP · transaction analysis" },
  { id: "openai", name: "OpenAI", initial: "O", color: "#10a37f", logo: null, state: "connected", detail: "Usage signals for ChatGPT Plus" },
  { id: "backboard", name: "Backboard", initial: "B", color: "#0d0d0f", logo: null, state: "connected", detail: "Memory & routing · synced 1m ago" },
  { id: "gemini", name: "Gemini", initial: "G", color: "#4285f4", logo: null, state: "connected", detail: "Decision engine · Careful mode" },
  { id: "tigerdata", name: "Tiger Data", initial: "T", color: "#f97316", logo: null, state: "connected", detail: "Usage events · 1,204 logged" },
  { id: "elevenlabs", name: "ElevenLabs", initial: "E", color: "#111", logo: null, state: "connected", detail: "Voice · Rachel, terse tone" },
  { id: "spotify-conn", name: "Spotify", initial: "S", color: "#1db954", logo: "/assets/logos/spotify.svg", state: "action", detail: "Reconnect to refresh play counts" },
];

export const user: DashboardUser = {
  name: "Mushtahir Kabir",
  role: "Account owner",
  email: "mushtahir@vouch.app",
  plan: "Vouch Pro",
  initials: "MK",
  memberSince: "Sep 2026",
};
